<?php

$ntb_st = get_option( 'news_ticker_benaceur_style' );
$ntb_enable_plug = get_option( 'news_ticker_benaceur_enable_plug' );
$ntb_delete_all_options = get_option( 'news_ticker_benaceur_delete_all_options' );
$ntb_group_reset = get_option('ntb_group_reset');
$ntb_group_anim_reset = get_option('ntb_group_anim_reset');
$ntb_group_sty_reset = get_option('ntb_group_sty_reset');
$ntb_all_reset = get_option('ntb_all_reset');
$ntb_links_admin_bar_front = get_option( 'news_ticker_benaceur_links_admin_bar_front' );
$ntb_links_admin_bar_menu = get_option( 'news_ticker_benaceur_links_admin_bar_menu');
$ntb_links_admin_bar_admin = get_option( 'news_ticker_benaceur_links_admin_bar_admin' );
$ntb_in_home = get_option( 'news_ticker_benaceur_in_home' );
$ntb_in_single = get_option( 'news_ticker_benaceur_in_single' );
$ntb_in_page = get_option( 'news_ticker_benaceur_in_page' );
$ntb_in_category = get_option( 'news_ticker_benaceur_in_category' );
$ntb_in_author = get_option( 'news_ticker_benaceur_in_author' );
$ntb_in_search = get_option( 'news_ticker_benaceur_in_search' );
$ntb_in_page_id = get_option( 'news_ticker_benaceur_in_page_id' );
$ntb_in_single_id = get_option( 'news_ticker_benaceur_in_single_id' );
$go_ea = get_option('news_ticker_benaceur_for_all_expt_admin');
$dir = get_option( 'news_ticker_benaceur_dir' );
$ntb_st = get_option( 'news_ticker_benaceur_style' );
$NTB_st_code = get_option( 'news_ticker_benaceur_ntb_st_code' );
$NTB_sht_code = "[wp_news_ticker_benaceur_short_code]";
$array_anim_two = array('ScrollNTB,Scroll_Up_NTB,fadein,TickerNTB');
$ntb_pause_scrollntb = get_option( 'news_ticker_benaceur_pause_scrollntb' );
$ntb_speed_scrollntb = get_option( 'news_ticker_benaceur_speed_scrollntb_' );
$ntb_ena_js_scrollntb = get_option( 'news_ticker_benaceur_ena_js_scrollntb' );
